### ISSUE TITLE
z-ordering sometimes off

### ISSUE THREAD

**Issue by Armag3ddon** [spuxx1701/potber-api#76]
Infrequently, a post overlaps the post menu and some menu items become inaccessible.

![image](https://github.com/spuxx1701/potber-api/assets/1497574/54fa851d-d005-4147-b536-ed01f22b6960)

A possible example for me was this post: [https://potber.de/thread?TID=219419&PID=1249954087](url)

**Comment by spuxx1701** [comment]
Wrong repository, but has been fixed in the meantime anyways
